name: tech-test
on: [push]
jobs:
  app-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install

      - name: Jest tests
        id: jest
        run: npm test

      - name: Cypress testing
        id: cypress
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start

      - name: Deployment
        if: steps.jest.outcome == 'success' && steps.cypress.outcome == 'success'
        run: npm run deploy
