name: tech-test
on: [push]
jobs:
  app-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install

      - name: Jest tests
        run: npm test
        run: npm start

      - name: Cypress testing
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start